## -----------------------------
## DATASOURCE PROPERTIES
## -----------------------------
spring.datasource.driver-class-name=org.postgresql.Driver

# --- APP DATABASE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/mediflow_db
spring.datasource.username=mediflow
spring.datasource.password=password123

# --- AUDIT DATABASE ---
spring.datasource.audit.url=jdbc:postgresql://localhost:5432/audit_db
spring.datasource.audit.username=mediflow
spring.datasource.audit.password=password123
spring.datasource.audit.driver-class-name=org.postgresql.Driver

## -----------------------------
## JPA / HIBERNATE
## -----------------------------
# APP DB - validate only
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=mediflow_schema

# Note: Audit DB Hibernate config will be in Java Config (AuditDataSourceConfig) with ddl-auto=update

## -----------------------------
## LOGGING
## -----------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

## -----------------------------
## MANAGEMENT ENDPOINTS
## -----------------------------
management.endpoints.web.exposure.include=health,info,metrics,env,beans,logfile,loggers
management.endpoint.health.show-details=always

## -----------------------------
## CUSTOM APPLICATION PROPERTIES
## -----------------------------
mediflow.validate.phone=false
mediflow.country.phone.prefix=+90
mediflow.country.code=TR

mediflow.appointment.start-time=08:00
mediflow.appointment.end-time=18:00
mediflow.appointment.duration=30

## -----------------------------
## DETAILED EXCEPTION PROPERTIES
## -----------------------------
mediflow.detailed.exception=false

## -----------------------------
## FLYWAY CONFIGURATION
## -----------------------------
# App DB Flyway migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

