CREATE TYPE specialty_enum AS ENUM ('CARDIOLOGY','DERMATOLOGY','HERMATOLOGY','NEUROLOGY','IMMUNOLOGY','INTERNAL_MEDICINE','EMERGENCY_MEDICINE','NEPHROLOGY','N/A');

ALTER TABLE mediflow_schema.doctors DROP COLUMN specialty;
ALTER TABLE mediflow_schema.doctors ADD COLUMN specialty specialty_enum NOT NULL DEFAULT 'N/A';
