package com.hospital.mediflow.Common.Events;

public enum EventType {
    APPOINTMENT_CREATED,
    APPOINTMENT_APPROVED,
    APPOINTMENT_SOON,
    APPOINTMENT_DONE,
    BILLING_DEPOSIT_CREATED,
    BILLING_TREATMENT_CREATED,
    BILLING_STATUS_UPDATED,
    BILLING_OVERDUE
}
